language: python
env:
  - testbin=unittest
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
install:
  - pip install -r requirements.txt
script: 
  - coverage run -m $testbin discover varints
after_success:
  - codecov
matrix:
  include:
    - python: "2.6"
      env:
        - testbin=unittest2.__main__
    
