language: python
env:
  - testbin=unittest
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script: 
  -  python -m $testbin discover varints
matrix:
  include:
    - python: "2.6"
      env:
        - testbin=unittest2.__main__
    
